stages:
  - test -- linux, shellcheck
  - test -- windows

git:
  depth: 1

jobs:
  include:
     - stage: test -- linux, shellcheck
       os: linux
       dist: xenial
       language: generic
       addons:
         apt:
           packages:
             - shellcheck
       script:
         - set -e

         - pushd tests/integration

         - shellcheck --shell=bash --external-sources --exclude=SC1090 run-all-tests.sh gitignore_test.sh gitattributes_test.sh
         - ./run-all-tests.sh

         - set +e

     - stage: test -- windows
       os: windows
       language: generic
       script:
         - set -e

         - pushd tests/integration

         - ./run-all-tests.sh

         - set +e
