stages:
  - test

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: test
       dist: trusty
       os: linux
       script:
         - set -e

         - touch foo.obj
         - git ls-files -o -i --exclude-standard > ignored.txt

         - diff ignored.txt tests/list-of-files-that-should-be-ignored.txt

         - set +e
