stages:
  - test

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: test
       dist: trusty
       os: linux
       script:
         - set -e

         - ls -la
         - git status

         - set +e
