stages:
  - test

jobs:
  include:
     - stage: test
       dist: trusty
       os: linux
       addons:
         apt:
           packages:
             - shellcheck
       script:
         - set -e

         - ./tests/run-all-tests.sh

         - set +e
