git:
  depth: 1

matrix:
  include:
     - name: "tests -- linux, shellcheck"
       os: linux
       dist: xenial
       language: generic
       addons:
         apt:
           packages:
             - shellcheck
       script:
         - set -e

         - pushd tests/integration
         - shellcheck --shell=bash --external-sources --exclude=SC1090 run-all-tests.sh gitignore_test.sh gitattributes_test.sh
         - ./run-all-tests.sh

         - set +e

     - name: "tests -- osx"
       os: osx
       osx_image: xcode10.1
       language: generic
       script:
         - set -e

         - pushd tests/integration
         - ./run-all-tests.sh

         - set +e

     - name: "tests -- windows"
       os: windows
       language: generic
       script:
         - set -e

         - pushd tests/integration
         - ./run-all-tests.sh

         - set +e
