stages:
  - test

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: test
       dist: trusty
       os: linux
       script:
         - set -e

         - touch foo.obj
         - git status
         - git status --ignored
         - git ls-files -o -i --exclude-standard

         - set +e
