stages:
  - test

env:
  global:
    - IGNORE_LIST="./ignored.txt"
    - IGNORE_LIST_REFERENCE="./tests/list-of-files-that-should-be-ignored.txt"

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - karelburda89@gmail.com

jobs:
  include:
     - stage: test
       dist: trusty
       os: linux
       script:
         - set -e

         - ./tests/run-all-tests.sh

         - set +e
