stages:
  - test

jobs:
  include:
     - stage: test
       dist: trusty
       os: linux
       addons:
         apt:
           packages:
             - shellcheck
       script:
         - set -e

         - pushd tests/integration
         - shellcheck --shell=bash --external-sources run-all-tests.sh gitignore_test.sh gitattributes_test.sh

         - ./run-all-tests.sh

         - set +e
